// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TTPay.Models.Data;

#nullable disable

namespace TTPay.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230417125439_NovacIntToDouble")]
    partial class NovacIntToDouble
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.15");

            modelBuilder.Entity("TTPay.Models.Susret", b =>
                {
                    b.Property<int>("SusretId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BojanPlatio")
                        .HasColumnType("REAL");

                    b.Property<double>("BojanPotrosio")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<double>("ManicPlatio")
                        .HasColumnType("REAL");

                    b.Property<double>("ManicPotrosio")
                        .HasColumnType("REAL");

                    b.Property<double>("ZecPlatio")
                        .HasColumnType("REAL");

                    b.Property<double>("ZecPotrosio")
                        .HasColumnType("REAL");

                    b.HasKey("SusretId");

                    b.ToTable("Susreti");
                });
#pragma warning restore 612, 618
        }
    }
}
